trilitech/tezedge

- .github/workflows/audit.yml
- .github/workflows/build.yml
- .github/workflows/clippy.yml
- .github/workflows/fuzzcheck.yml
- .github/workflows/rustfmt.yml
Enable CI for builds/PRs.
Switches away from `actions-rs` as this is unmaintained. See [thread](https://github.com/actions-rs/toolchain/issues/216)
> CI: enable github workflows

- Cargo.lock
- crypto/Cargo.toml
- crypto/src/base58.rs
sodiumoxide doesn't support compilation to wasm
> crypto: replace digest implementation

- .github/workflows/build.yml
As crypto & tezos_encoding are used by kernels, these crates must support compilation to wasm32-unknown-unknown out-of-the-box.
> CI: ensure wasm compilation supported

- crypto/Cargo.toml
This reverts commit 799a678c3d70bf7f3da01e64740e6deee5feacac. Blst cannot be downgraded, without also downgrading zeroize to a version with a known RUSTSEC issue
> Revert "crypto: synchronise blst version with octez"

- .github/workflows/publish.yml
- CHANGELOG.md
- README.md
- crypto/Cargo.toml
- tezos-encoding-derive/Cargo.toml
- tezos-encoding/Cargo.toml
Follow up from #26 - which only published `tezos_data_encoding_derive`
> CI: publish all crates in workspace

- .github/workflows/publish.yml
Will ensure that multiple crates update at the same time.
> CI: publish crate after dry-run

- .github/workflows/publish.yml
- CHANGELOG.md
- crypto/Cargo.toml
- tezos-encoding-derive/Cargo.toml
- tezos-encoding/Cargo.toml
(bump version due to `tezos_data_encoding_derive` published @ 0.4.2)
> publish 0.4.3 to crates.io

- .github/workflows/publish.yml
- Cargo.lock
Before, publishing each crate happened in separate steps within the same job. If `crates.io` didn't update its index fast enough, however, then the final `tezos_crypto_rs` deploy could fail as it wouldn't be able to find it's dependencies yet.
Therefore, we split them into separate jobs, to allow manual retry of publishing if crates.io is slow updating
> CI: run deploys in separate jobs, allowing retry

- tezos-encoding-derive/src/bin.rs
- tezos-encoding-derive/src/enc.rs
- tezos-encoding-derive/src/lib.rs
- tezos-encoding-derive/src/make.rs
- tezos-encoding-derive/src/nom.rs
- tezos-encoding/src/lib.rs
Derivations of encodings previously running against the old `tezos_encoding` crate name.
To ensure this doesn't happen again, we add a doc test showcasing derivation to ensure encodings work correctly.
> tezos_data_encoding_derive: fix derivations

- .github/workflows/audit.yml
- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.lock
- crypto/Cargo.toml
- crypto/src/bls.rs
- crypto/src/hash.rs
- crypto/src/lib.rs
We moved away from `dalek` due to a previous [security issue](https://github.com/hyperledger/ursa/issues/209). 
This has now been fixed, and so we move back to the latest release of dalek, as it runs much faster than `compact`.
*NB* the API of `verify` has changed, to only accept a single `AsRef<[u8]>`, as the hashing is done internally by dalek.
> crypto: switch to ed25519_dalek

- CHANGELOG.md
- Cargo.lock
- crypto/Cargo.toml
- tezos-encoding-derive/Cargo.toml
- tezos-encoding/Cargo.toml
When creating a new project with Smart Rollup of Tezos, the `bst` dependency of `crypto` is resolved to the version `0.3.11` which does not build to `wasm32-unknown-unknown`
Force the version of `blst` to be `0.3.10`. Only this crate can be updated/published, it's not necessary to update the crates that depends on this one, because new projects will automatically use the version 0.5.1 of `crypto`.
> crypto: fix the version of blst to 0.3.10

- CHANGELOG.md
- tezos-encoding-derive/src/nom.rs
- tezos-encoding/src/lib.rs
- tezos-encoding/src/nom.rs
- tezos-encoding/src/types.rs
The `NomReader` trait is implicitly parameterized by the lifetime of the input byte slice. This commit makes the quantification on this explicit. This is needed to implement `NomReader` for structures which keep a reference to some slice of the input, for example to implement lazy deserialization.
> tezos-encoding + derive: keep track of lifetime in NomReader

- CHANGELOG.md
- crypto/src/hash.rs
fixes #44 
See https://gitlab.com/tezos/tezos/-/merge_requests/11286 for corresponding fix in TX_KERNEL
> crypto: ed25519 signing should hash input

- CHANGELOG.md
- Cargo.lock
- crypto/Cargo.toml
- crypto/src/base58.rs
- crypto/src/hash.rs
The current base58 module incorrectly had a `128` char limit set on decoding hashes - too small for `bls sigs`. We raise this limit to the length of `BlsSigs` hashes, which are the longest hashes we support.
fixes #49
> crypto: fix base58 encoding for BlsSignature

- CHANGELOG.md
- crypto/src/blake2b.rs
- crypto/src/hash.rs
- crypto/src/lib.rs
- crypto/src/signature.rs
- tezos-encoding/src/enc.rs
- tezos-encoding/src/encoding.rs
- tezos-encoding/src/nom.rs
> crypto: align Signature with octez crypto impl

- CHANGELOG.md
- crypto/src/hash.rs
The previous base58 check encoding was incorrectly using the legacy format, where the encoded key was actually the concatenation of `sk` + `pk`.
fixes #45
> crypto: remove legacy base58 encoding for SecretKeyEd25519

- CHANGELOG.md
- crypto/src/base58.rs
- crypto/src/hash.rs
- crypto/src/signature.rs
This allows ToBase58Check to no longer return results, since we know the hashes will _always_ be correctly constructed.
> crypto: do not make inner hash public

- CHANGELOG.md
- crypto/src/hash.rs
- crypto/src/signature.rs
Currently defaults to Ed25519, which does not match octez reference
Fixes #50
> crypto: Signature of all zero bytes should be Unknown

- CHANGELOG.md
- crypto/src/hash.rs
- crypto/src/signature.rs
we update `verify_sig` impls to require the specific signature type for the key being used.
To ease use with `Signature` enum, we provide `TryFrom<Signature> for <SigType>` impls.
Closes #52 
*NB* this does slightly the opposite of what was requested in #52. It's addressed, however, as it is much easier now to convert too the correct signature type, to pass through.
The corresponding `PublicKey` type in the SDK, will be able to use this to greater effect, and can indeed receive the more general `Signature` type.
This layout/structure is more in-line with the `signature` module provided in `octez/tezos_crypto`.
> crypto: verify sig should be more specific

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.lock
- crypto/Cargo.toml
Improves RISC-V compatibility.
> crypto: Bump blst to 0.3.12

- CHANGELOG.md
- Cargo.lock
- crypto/Cargo.toml
- tezos-encoding/Cargo.toml
Bump `num-bigint -> 0.4`.
Additionally disable default-features. 
This prevents floating point operations being included, which caused issues when targetting wasm
> deps: upgrade num-bigint

- CHANGELOG.md
- tezos-encoding-derive/src/encoding.rs
- tezos-encoding-derive/src/make.rs
- tezos-encoding-derive/src/nom.rs
- tezos-encoding-derive/src/symbol.rs
- tezos-encoding/src/nom.rs
Remove the `hashed` field kind from data encoding. As far as I can see we've never used this - and does not appear particularly applicable outside of what tezedge may well have been doing in the past as part of the shell work.
This allows swapping the dependency ordering between `tezos_crypto_rs` & `tezos_data_encoding` in #72
> encoding: remove hash field kind

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crypto/Cargo.toml
- crypto/src/hash.rs
- crypto/src/hash/encoding.rs
- crypto/src/signature.rs
- tezos-encoding/Cargo.toml
- tezos-encoding/src/enc.rs
- tezos-encoding/src/encoding.rs
- tezos-encoding/src/lib.rs
- tezos-encoding/src/nom.rs
Allows using `derive` macros when adding aggregate types #73
> crypto/encoding: swap dependency direction

- CHANGELOG.md
- crypto/src/lib.rs
- crypto/src/public_key.rs
- crypto/src/public_key_hash.rs
Closes RV-10
two commits:
1. copy of the module text directly
2. integrating the modules into the crypto crate
> crypto: add PublicKey(Hash) types from SDK

- CHANGELOG.md
- crypto/src/hash.rs
- crypto/src/public_key.rs
> crypto: tz2 should hash input
